// Vercel Edge Function: subscribable calendar feed (webcal/ics).
// Apple Calendar and Google Calendar poll this URL; the token is a secret
// capability created by the app (calendar_feeds table) and revocable there.
export const config = { runtime: 'edge' }

declare const process: { env: Record<string, string | undefined> }

import type { Item } from '../src/types'
import { buildRemindersIcs } from '../src/lib/ics'

interface FeedItemRow {
  id: string
  name: string
  kind: Item['kind']
  amount: number | string
  currency: Item['currency']
  frequency: Item['frequency']
  startDate: string
  installmentsTotal: number | null
  paidDates: string[]
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'GET') return new Response('Method not allowed', { status: 405 })
  const token = new URL(req.url).searchParams.get('t') ?? ''
  if (!UUID_RE.test(token)) return new Response('Not found', { status: 404 })

  const supabaseUrl = process.env.VITE_SUPABASE_URL
  const anonKey = process.env.VITE_SUPABASE_ANON_KEY
  if (!supabaseUrl || !anonKey) return new Response('Not configured', { status: 501 })

  const rpc = await fetch(`${supabaseUrl}/rest/v1/rpc/calendar_feed_data`, {
    method: 'POST',
    headers: {
      apikey: anonKey,
      authorization: `Bearer ${anonKey}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({ feed_token: token }),
  })
  if (!rpc.ok) return new Response('Upstream error', { status: 502 })
  const data: { lang?: string; items?: FeedItemRow[] } | null = await rpc.json()
  if (!data) return new Response('Not found', { status: 404 })

  const lang = data.lang === 'en' ? 'en' : 'pt'
  const locale = lang === 'pt' ? 'pt-BR' : 'en-AU'
  const money = (n: number, currency: Item['currency']) =>
    `${currency === 'AUD' ? 'A$' : 'R$'} ${new Intl.NumberFormat(locale, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(n)}`
  const dayFmt = new Intl.DateTimeFormat(locale, { weekday: 'short', day: 'numeric', month: 'short' })
  const fmtDay = (iso: string) => {
    const [y, m, d] = iso.split('-').map(Number)
    return dayFmt.format(new Date(Date.UTC(y, m - 1, d)))
  }

  const rows = data.items ?? []
  const items: Item[] = rows.map((r) => ({
    id: r.id,
    kind: r.kind,
    name: r.name,
    category: 'other',
    amount: Number(r.amount),
    currency: r.currency,
    owner: 'shared',
    frequency: r.frequency,
    startDate: r.startDate,
    installmentsTotal: r.installmentsTotal,
    notes: null,
    archived: false,
    createdAt: '',
  }))
  const paidByItem = new Map(rows.map((r) => [r.id, new Set(r.paidDates ?? [])]))

  const title = (i: Item, due: string) =>
    lang === 'pt'
      ? `💸 Pagar ${i.name} amanhã — ${money(i.amount, i.currency)} (${fmtDay(due)})`
      : `💸 Pay ${i.name} tomorrow — ${money(i.amount, i.currency)} (${fmtDay(due)})`
  const body = (_i: Item, due: string) =>
    lang === 'pt'
      ? `Vence em ${fmtDay(due)}. Gerado pelo Contas do Casal.`
      : `Due ${fmtDay(due)}. Generated by Contas do Casal.`

  const ics = buildRemindersIcs(items, title, body, {
    feedName: 'Contas do Casal',
    skip: (i, due) => paidByItem.get(i.id)?.has(due) ?? false,
  })

  return new Response(ics, {
    headers: {
      'content-type': 'text/calendar; charset=utf-8',
      'cache-control': 'public, max-age=1800',
      'content-disposition': 'inline; filename="contas-casal.ics"',
    },
  })
}
